include ../../Makefile.conf

MODULE_NAME = Hybrid A* IPC Messages
MODULE_COMMENT =

CFLAGS += #-pg #-fopenmp
CXXFLAGS += #-pg #-fopenmp

SOURCES = hybrid_astar_interface.cpp

PUBLIC_INCLUDES = hybrid_astar_messages.h hybrid_astar_interface.h

include ../../Makefile.rules
